### ISSUE TITLE
Proposal Review

### ISSUE THREAD

**Issue by Chris210634** [xud0218/ClimaTrade#1]
This is a confusing proposal. I am not sure if you want to predict the next day's weather based on historical weather data or predict stock market based on the weather. They seem to be two separate projects to me. 

My suggestion is to first gather some historical weather data for NYC and try to find correlations between that data and stock market data. This by itself could be interesting.

**Comment by xud0218** [comment]
Sorry for the vague; I have revised the proposal for a clearer description. 
I appreciate your additional time to review my proposal.

**Comment by Chris210634** [comment]
I looked at the revised proposal and don't have any further comments.
